version: '3.9'

services:
  webcheck:
    container_name: webcheck
    image: lissy93/web-check
    ports:
      - 6160:3000
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5